package de.hahn.blog.test1213.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 17 11:30:53 CEST 2014
// ---------------------------------------------------------------------
public interface LocationsView extends ViewObject {
    String getbindCity();

    void setbindCity(String value);

    void findCityByName(String name);
}

