package de.hahn.blog.test1213.model.adfbc.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 14 16:34:41 CET 2014
// ---------------------------------------------------------------------
public interface BT1213AppModule extends ApplicationModule {
    oracle.jbo.domain.Number nextVal();
}

