package de.hahn.blog.test1213.model.adfbc.views;

import de.hahn.blog.test1213.model.adfbc.views.common.LocationsView;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 17 11:30:45 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocationsViewImpl extends ViewObjectImpl implements LocationsView {
    /**
     * This is the default constructor (do not remove).
     */
    public LocationsViewImpl() {
    }

    /**
     * Returns the variable value for bindCity.
     * @return variable value for bindCity
     */
    public String getbindCity() {
        return (String) ensureVariableManager().getVariableValue("bindCity");
    }

    /**
     * Sets <code>value</code> for variable bindCity.
     * @param value value to bind as bindCity
     */
    public void setbindCity(String value) {
        ensureVariableManager().setVariableValue("bindCity", value);
    }

    public void findCityByName(String name) {
        String[] applyViewCriteriaNames = getApplyViewCriteriaNames();
        if (applyViewCriteriaNames != null) {
            for (String cname : applyViewCriteriaNames) {
                removeApplyViewCriteriaName(cname);
            }
        }
        ViewCriteria criteria = getViewCriteria("LocationsViewCriteria");
        setbindCity(name);
        applyViewCriteria(criteria);
        executeQuery();
    }
}

